name: precommit

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  precommit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-python@v6
        with:
          python-version: 3.13
      - run: |
          pip install pre-commit
          pre-commit run --all-files --show-diff-on-failure 